version: '2'
services:
  ${rabbit_service_name}:
    image: rabbitmq:management
    ports:
     - "${rabbit_port}:5672"
     - "${rabbit_admin_port}:15672"
    networks:
      ${network}:
        aliases: []
networks:
  ${network}: {}

