version: '3'
services:
  storageCassandra:
    image: cassandra
    ports:
      - "9042:9042"
    networks:
      net:
        aliases: []
  storage:
    image: ncei/metadata-catalog-storage:0.1.0
    ports:
     - "8081:8080"
    environment:
     - cassandra_contactPoints=storageCassandra
    depends_on:
     - wait
    volumes:
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_application.sh
    networks:
      net:
        aliases: []
  wait:
    image: cassandra
    depends_on:
     - storageCassandra
    volumes:
     - ../cql:/tmp/cql:ro
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/initialize_cassandra.sh
    networks:
      net:
        aliases: []
networks:
  net : {}
