version: '2'
services:
  ${cassandra_service_name}:
    image: cassandra
    ports:
      - "${cassandra_port}:9042"
    networks:
      ${network}:
        aliases: []
  ${rabbit_service_name}:
    image: rabbitmq:management
    ports:
     - "${rabbit_port}:5672"
     - "${rabbit_admin_port}:15672"
    networks:
      ${network}:
        aliases: []
networks:
  ${network}: {}
