version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      net:
        aliases: []
  rabbit:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      net:
        aliases: []
networks:
  net: {}
