elasticsearch:
  cluster:
    name: <elasticsearch_cluster>
  host: localhost
  port: 9300

rabbitmq:
  connectionfactory:
    host: localhost
    virtualHost: /
    username: guest
    password: guest