sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: qn++j/DOz2A8rz3ebvWIvf4pMm013XV3t0Iqa7jfQYT5aovA9Hc8vO+1g3seZPOpElivs5lMT9i+UIRXC0gPfB4R9RgT+L4+qvn6KHRDsYMEQv2+8rVqOH6B8+REAzhJj45AhszVkpCKxxYsxFjwfNma+2SFM/biYH5X+zb2yKNrsDHcXIC1/viGnZVtngjUm4ldlsKk/eCuRuISeuuQ5kGc4hafNBUxfiuN314fOTwSrFMWnpZK4uXV2K9/yE4YaxjvMs79DEWfHsvuqe8YsEJ16iN08G6++1zbVpBigSmveAapdM+4SqDNf5A9uhlN2loKU8+YjPN3wFmUOy3LbCb7nUJOyEpZ9On9wCo7gKO8sUmKT26crzqNh2t38U7a5mqYl/MUuwZRqMhlJg5ALZjclfxa+t5MlUpwW4Eu/Pc7Dj1tkjyIFtzftvCaFpw7i68e7MIWlDBqw5o131nT0gW+S3kJGEiMItG7SdyfN7sDwklvOgJ6Sf+Hm/5ASJkJdShHJJVSv7x9fixRGj66Wxhi64/YpdZ5/k4VX50YDgd2j66ORI+0zrmcA6oozIJYTKpashSJz9W/lprNRcLstmDBQQykbhrFk247jzTCkXyLFKG5cOhxxhzt6gg0JRM3Vn7r/nLM69H/jU0m0ZpOARtqdutfgBXb8nDWN7+RYtg=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
env:
  global:
    - secure: Q2s0mp90R9uxIXulMF5vR92rOadQSG9c3E9ZX3MvsQvm6rKx2mIMgUiXgYdGseUaFf0OXNat06fWhjufa/2C8mMX4kxR5+o7ov2IGM9tRZJAdZ1RjM5PE1gIv1P8gcEk9tNt/zIy/40X3fxwn8NEGY8YpPOEyAytjayQgD8MAJEBg58Cx+rRvXyOXH4Zv5u4RhiWOWuQMWG0FLeP+oRCK3pckP81yArlF/sxFYbfttBY5aGgSONHUhPY85Fddqojij3P6+Aa3dxhRvR36KeNgS4/1Zq9htg3IOaIoP8iQrPJWypJcmeZr3r3SCxr4T7tnyk0P+ww1dncigJlCanZtfv/B4o8a8vp/QwRVmXZDGYdHH8NMbrWPkvssgqnha8+zqJQdaceXlI62xkKDBTAYqlUxaSEqIQPoV6mF+OaVAUSNeRpuQgxdpgN25cl8nUnnidbgJSwgVjopPzla1iwfLs0x4mkW6PXsy3vApb8GYbysTSYl7C+qvl2Fp7/WtCkWRP4GD6eT0Cq9qiwrZAcPkcbcJ7MkApoQJ3sLW2zqUBYNmLwQLh7/F1zGkuHNLspbn1Mlu938EoH7s91kChJE3MUs8E/T+LEEqBXA1Ru0h0vezCL+UG7e5KJgfNO/KdZyRP2JwsFMUz9ycn40y3wO6j+x8UNTAtBP1HoZrsq7ZY=
    - secure: hNUWiX6/fKP8k7/5fcIpGe3WZzjNF0xSl25kRuFXiVNyvPAI0KtENS0yjcNPdAgs+Kisr89o/fipLL/IRYfjBBJsC8gOt1fntPgJG9OtDGQnqsQ24zo0nUCNyfvfkYroz6jG4iokjpwxl+gB8IsXU9hqjDSJkOwr3tLrVrZULzTIrPatrvchVQImW1ZyI1deUyxJ4KBqBbZ2UamAoyMWVrvqC83sbFDa7yFrKt6M6V/RgPOh0B/yeraG0ARWoDbAKWHgZkyImsGNOD0KLEcnhjbQWui9QOQcZGRLG51nxOG4Cw5hbjyKmcBSmOXgLCYeE4EcQNVbonVhZU8np8nifnAIceJgqC1j1vgZZDwoK76gFgUPJB23jf6SPP5xuMb/D4ol1cLf0D0wgzy1fovXVhsg/zVZDgOjjyfnyuol9YR/P5g6/w/5vrPSVFgE2WT8A8KXTUzn99aSxZnPTPy7O56SS91h6QKdulRtvqNyK8QUFGkHATeTu+KYy4ElicsW+3NYRJSvLf+X/DmzjPO6SCj43BA18Abpk4BQUJ+Xepgklc4AkKNCLNl3+Ljs3K31MnBVyirAciKlTEGwtODeB3CmHHbFwpdlDXnkk1+VfIfYaB3geynOzMhvSPjedbjw9hHheWHLy8SpgVhxhVowGieoCLttUDnjH43ZbTkFrRs=
before_install:
  - sudo sysctl -w vm.max_map_count=262144
install: true
script:
  - ./gradlew clean build publishImage artifactoryPublish -Dscan
after_failure:
  - ./gradlew debugDockerLogs dockerComposeDown
deploy:
  # publish SNAPSHOT build and images to artifactory for everything on master
  #provider: script
  #script: ./gradlew publishImage artifactoryPublish
  #on:
  #  branch: master
  # run promote if the commit was tagged with a version
  provider: script
  script: bash -c "if [[ $(git tag -l --points-at HEAD) == v* ]]; then ./gradelw promote; fi"
  on:
    tags: true
  #  branch: master # I think it may ignore this value, but if snapshots don't exist on branches what happens?
