version: '2'
services:

  ${api_service_name}:
    image: ${api_image}
    ports:
     - "${api_port}:8080"
    environment:
     - rabbitmq_connectionfactory_host=${rabbit_service_name}
    volumes:
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_api.sh
    networks:
      ${network}:
        aliases: []

  ${rabbit_service_name}:
    image: rabbitmq:management
    ports:
     - "${rabbit_port}:5672"
     - "${rabbit_admin_port}:15672"
    networks:
      ${network}:
        aliases: []

  ${elasticsearch_service_name}:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "${elasticsearch_rest_port}:9200"
      - "${elasticsearch_node_port}:9300"
    networks:
      ${network}:
        aliases: []
  ${index_service_name}:
    image: ${index_image}
    ports:
     - "${index_port}:8080"
    environment:
     - elasticsearch_host=${elasticsearch_service_name}
     - rabbitmq_connectionfactory_host=${rabbit_service_name}
    volumes:
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_index.sh
    networks:
      ${network}:
        aliases: []

  ${cassandra_service_name}:
    image: cassandra
    ports:
      - "${cassandra_port}:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    networks:
      ${network}:
        aliases: []
  ${storage_service_name}:
    image: ${storage_image}
    ports:
     - "${storage_port}:8080"
    environment:
     - cassandra_contactPoints=${cassandra_service_name}
     - rabbitmq_connectionfactory_host=${rabbit_service_name}
    depends_on:
     - ${cassandra_initialization_service_name}
    volumes:
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_storage.sh
    networks:
      ${network}:
        aliases: []
  ${cassandra_initialization_service_name}:
    image: cassandra
    depends_on:
     - ${cassandra_service_name}
    volumes:
     - ./cql:/tmp/cql:ro
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/initialize_cassandra.sh
    networks:
      ${network}:
        aliases: []

networks:
  ${network}: {}

