version: '3'

services:

  ${api_service_name}:
    image: ${api_image}
    ports:
     - "${api_port}:8080"
    environment:
     - index_host=${index_service_name}
     - index_port=${index_port}
     - storage_host=${storage_service_name}
     - storage_port=${storage_port}

  ${rabbit_service_name}:
    image: rabbitmq:management
    ports:
     - "${rabbit_admin_port}:15672"

  ${elasticsearch_service_name}:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false

  ${index_service_name}:
    image: ${index_image}
    environment:
     - elasticsearch_host=${elasticsearch_service_name}
     - rabbitmq_connectionfactory_host=${rabbit_service_name}

  ${cassandra_service_name}:
    image: cassandra:3.10

  ${cassandra_initialization_service_name}:
    image: ${cassandra_image}
    depends_on:
     - ${cassandra_service_name}
    deploy:
     restart_policy:
       condition: on-failure

  ${storage_service_name}:
    image: ${storage_image}
    environment:
     - cassandra_contactPoints=${cassandra_service_name}
     - rabbitmq_connectionfactory_host=${rabbit_service_name}
    depends_on:
     - ${cassandra_initialization_service_name}
