spring.main.show_banner: false

server:
  port: 8080
  context-path: /

spring:
  application:
    name: api
  cloud:
    discovery:
      enabled: false

index:
  host: localhost
  port: 8082

storage:
  host: localhost
  port: 8081

zuul:
  routes:
    metadata-catalog-granules:
      path: /metadata-catalog/granules/**
      url: http://${storage.host}:${storage.port}/granules/
    metadata-catalog-search:
      path: /metadata-catalog/search/**
      url: http://${index.host}:${index.port}/search/
    storage:
      path: /storage/**
      url: http://${storage.host}:${storage.port}
    index:
      path: /index/**
      url: http://${index.host}:${index.port}
    ecs-catalog:
      path: /ecs-catalog/**
      url: http://${storage.host}:${storage.port}
