version: '2'
services:
  ${elasticsearch_service_name}:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false
    ports:
      - "${elasticsearch_rest_port}:9200"
      - "${elasticsearch_node_port}:9300"
    networks:
      ${network}:
        aliases: []
  ${index_service_name}:
    image: ${index_image}
    ports:
     - "${index_port}:8080"
    environment:
     - elasticsearch_host=${elasticsearch_service_name}
     - rabbitmq_connectionfactory_host=${rabbit_service_name}
    volumes:
     - ./scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_index.sh
    networks:
      ${network}:
        aliases: []
networks:
  ${network}: {}

