---
cassandra:
  keyspace: 'metacat'
  port: '9042'
  contactPoints: 'localhost'

server:
  context-path: /metadata-catalog

rabbitmq:
  queue: index-consumer
  connectionfactory:
    host: localhost
    virtualHost: /
    username: guest
    password: guest