---
cassandra:
  keyspace: 'metacat'
  port: '9042'
  contactPoints: 'localhost'

server:
  context-path: /metadata-catalog
  error.whitelabel.enabled: false

rabbitmq:
  queue: index-consumer
  connectionfactory:
    host: localhost
    virtualHost: /
    username: guest
    password: guest

spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
