version: '2'
services:
  rabbit:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      net:
        aliases: []

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      net:
        aliases: []
  index:
    build:
      context: ../index/
      args:
        NAME: "index"
        VERSION: ${VERSION}
        DATE: ${DATE}
    ports:
     - "8082:8080"
    environment:
     - elasticsearch_host=es
     - rabbitmq_connectionfactory_host=rabbit
    volumes:
     - ./resources/docker/scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_index.sh
    networks:
      net:
        aliases: []

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    networks:
      net:
        aliases: []
  storage:
    build:
      context: ../storage/
      args:
        NAME: "storage"
        VERSION: ${VERSION}
        DATE: ${DATE}
    ports:
     - "8081:8080"
    environment:
     - cassandra_contactPoints=cassandra
     - rabbitmq_connectionfactory_host=rabbit
     - cassandra_init=true
    volumes:
     - ./resources/docker/scripts:/tmp/scripts:ro
    command: /bin/bash /tmp/scripts/start_storage.sh
    networks:
      net:
        aliases: []


networks:
  net: {}
